site_name: JACE (JSON Agent Context Envelope)
site_url: https://jace-spec.github.io
repo_url: https://github.com/jace-spec/spec
theme:
  name: material
  features:
    - navigation.instant
    - search.highlight
markdown_extensions:
  - admonition
  - toc:
      permalink: true
nav:
  - Overview: overview.md
  - Getting Started: getting-started.md
  - Core Concepts: concepts.md
  - Real-World Usage: real-world.md
  - Runtime / Sandbox: runtime-sandbox.md
  - Security: security.md
  - FAQ: faq.md
  - Roadmap: roadmap.md
  - Specs:
      - Content Negotiation: specs/content-negotiation.md
      - Errors: specs/errors.md
      - Pagination: specs/pagination.md
      - ARIA Mapping: specs/aria-mapping.md
  - Schemas:
      - jace-view.schema.json: schemas/jace-view.schema.json
      - jace-view.agent.schema.json: schemas/jace-view.agent.schema.json
      - jace-action.schema.json: schemas/jace-action.schema.json
      - jace-action-result.schema.json: schemas/jace-action-result.schema.json
      - jace-event.schema.json: schemas/jace-event.schema.json
  - Snippets: snippets.md
